### ISSUE TITLE
IllegalStateException: Untracked files

### ISSUE THREAD

**Issue by nachtien** [apollographql/update-graphql-schema#2]
My workflow looks like this:

```
name: Update GraphQL schema
# Check every night at midnight
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      X_ADMIN_TOKEN: ${{ secrets.X_ADMIN_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update **** schema
        uses: apollographql/update-graphql-schema@main
        with:
          endpoint: "https://*******.com/graphql"
          schema: "grapqhql-model/src/main/graphql/****/schema.graphqls"
          headers: '{"X-Admin-Token": "****"}'
      - name: Update **** schema
        uses: apollographql/update-graphql-schema@main
        with:
          endpoint: "https://api.****.com/api/gql"
          schema: "grapqhql-model/src/main/graphql/****/schema.graphqls"
```

The exception is:

```
Switched to a new branch 'update-schema-06-02_10-49'
java.lang.IllegalStateException: Command git -c user.name=github-actions[bot] -c user.email=github-actions[bot]@users.noreply.github.com commit -a -m Update GraphQL Schema --author nachtien <nachtien@users.noreply.github.com> failed with exitCode '1'
output was: On branch update-schema-06-02_10-49
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	grapqhql-model/

nothing added to commit but untracked files present (use "git add" to track)

	at Update_schema_main.executeCommand(update-schema.main.kts:34)
	at Update_schema_main.run(update-schema.main.kts:113)
	at Update_schema_main.<init>(update-schema.main.kts:126)
Error: Invalid status code: 3
    at ChildProcess.<anonymous> (/home/runner/work/_actions/apollographql/update-graphql-schema/main/index.js:17:19)
    at ChildProcess.emit (events.js:314:[20](https://github.com/****/****_Android/runs/6706892945?check_suite_focus=true#step:3:21))
    at maybeClose (internal/child_process.js:10[22](https://github.com/****/****_Android/runs/6706892945?check_suite_focus=true#step:3:23):16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:[28](https://github.com/****/****_Android/runs/6706892945?check_suite_focus=true#step:3:29)7:5) {
  code: 3
}
Error: Invalid status code: 3
    at ChildProcess.<anonymous> (/home/runner/work/_actions/apollographql/update-graphql-schema/main/index.js:17:19)
    at ChildProcess.emit (events.js:[31](https://github.com/****/****_Android/runs/6706892945?check_suite_focus=true#step:3:32)4:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
